### PR TITLE
[FEATURE] Add Data API get items test

### PR DESCRIPTION
**Pull request by gonzalozawa**

### CODE REVIEW

**Comment by gonzalozawa** [comment]
@karoltarasiuk, based on @shtrom comments in Slack about the SDK TLS version issue, I have added a test to the Unit Tests project to test the Data API. It is a very simple get items request. I had to manually change the endpoint to test staging for this particular issue, I don't want to commit a staging url.
Anyway, I would like to know your comments about this and also take this opportunity to identify if there is a need for other tests that I could work and add to the project. Thanks! :)

**Comment by shtrom** [comment]
Hey @gonzalozawa. This is great, thanks for doing that! My .NET is not up to scratch, so I can't review in details, but it looks good. If possible, I wonder if this new test good be put into a separate _integration_ test suite.

As for the URL to hit, you can determine it programatically based on the ENV/REGION/VER environment variable. I have some variation of this algorithm in all the other SDKs:

https://github.com/Learnosity/learnosity-sdk-java/blob/13ba510c32c7e11dca1bb028685e5fa2b8db01fa/src/test/java/learnositysdk/request/DataApiIT.java#L174-L192

So we can specify which host to hit without having to change the code.

Side question: how to we run that test suite from the CLI?

**Comment by gonzalozawa** [comment]
@shtrom, thanks for your comments :)

I am not sure if it is possible to use the Visual Studio CLI to run the tests on a Mac. So we have two options here:
1. Use a Windows machine or VM
2. Use Visual Studio for Mac IDE (https://www.visualstudio.com/vs/mac/) to run the tests project on a Mac.
My Windows VM is broken at the moment so I am using VS for Mac and it is working fine for the moment.

Is your plan to have these integration tests running automatically at some point?

**Comment by shtrom** [comment]
Ok, it doesn't. but it shouldn't be too far off. Leaving the following for reference.

A base `.travis.yaml`, according to [0], would be 
```
language: csharp
mono: none
dotnet: 1.1.5
script:
 - dotnet build
 - dotnet test
```

[0] https://docs.travis-ci.com/user/languages/csharp/

**Comment by shtrom** [comment]
LRN-19680

**Comment by gonzalozawa** [comment]
@karoltarasiuk thanks for the review! :)
I've done a couple of tests to fix the warnings and build errors in Travis. Now everything should be working fine! https://travis-ci.org/Learnosity/learnosity-sdk-asp.net

**Comment by karoltarasiuk** [comment]
@gonzalozawa nice good effort!

**Pull request merged**
