### PR TITLE
[BUG] Added support for NULL values

### PR DESCRIPTION
**Pull request by karoltarasiuk**

### CODE REVIEW

**Comment by karoltarasiuk** [comment]
@gonzalozawa please review this PR, and also if you could do some mini func on it. If all good please merge, thanks!

**Comment by gonzalozawa** [comment]
Hi @karoltarasiuk thanks for the quick response on this! Testing the PR I found that the null value index the array change. For example having "value":[null, [2]] the result I get now is "value":[[2], null]
Do you think that this could cause issues?

**Comment by karoltarasiuk** [comment]
@gonzalozawa yes it definitely will, I will need to add some unit tests to cover this then... thanks!

**Comment by karoltarasiuk** [comment]
@gonzalozawa fixes applied, should be OK now. Let me know

**Comment by gonzalozawa** [comment]
@karoltarasiuk this is looking good now! I have tested it and it works as expected. Great to see the unit tests. For some reason I can't run the unit test in VS2015. They work fine in VS2013. Should we add a comment regarding the unit tests in the readme file? Now they are part of the solution and clients will get that project as part of it. What do you think?

**Pull request merged**
